### PR TITLE
Performance improvements

### PR DESCRIPTION
**Pull request by danse**
It is probably better to watch at this with `w=1` to ignore indentation changes in the test file

### CODE REVIEW

**Comment by rmehner** [comment]
Tested this and this is definitely faster, still 2s on my desktop machine in the follow up app though. But with the changes from your branch `new-locations-francesco` it works fast now.

Good work & thank you!

**Comment by rmehner** [comment]
Discussing the UX with @FrancescoK at the moment, not sure if that progressive disclosure works with our users. So I'm gonna merge this, as this is definitely better as before and then we can discuss the other changes at their place.

**Comment by danse** [comment]
Cool, i can hardly imagine any user wishing to pick from 13000 select options, but i will wait for reasons :)

**Comment by rmehner** [comment]
We couldn't either, but we wanted to discuss this first to make sure we're all on the same side :) Decided to use the progressive selection mode that is coming to a pull request near you very soon :)

**Pull request merged**
